FROM node:20-slim

WORKDIR /app

COPY package.json yarn.lock ./
COPY .env .env

RUN corepack enable && yarn config set nodeLinker node-modules && yarn install

COPY . .

EXPOSE 5173

CMD ["yarn", "start:dev"]
