name: Frontend Deploy

on:
  push:
    branches:
      - deploy
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Enable Corepack and install Yarn 4.8.1
        run: |
          corepack enable
          corepack prepare yarn@4.8.1 --activate
        
      - name: Install dependencies
        run: yarn install --immutable
        
      - name: Build frontend
        run: yarn start:build

      - name: Copy build to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/hwat.pro"

      - name: Reload nginx on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: sudo systemctl reload nginx
